### ISSUE TITLE
CLI v 0.102.0 doesn't contain add dependency for dendron-viz

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3189]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After upgrading to v0.102.0 using `yarn` on windows all dendron commands are giving error where module `@dendronhq/dendron-viz` is not found. This dependency needs to be manually added using `yarn add @dendronhq/dendron-viz` first.

## To Reproduce

1. Ensure you do not currently have the dendron-viz module installed or part of your dependencies in your yarn lock file
2. `yarn upgrade @dendronhq/dendron-cli@latest`
3. `npx dendron --version`
5. `yarn add @dendronhq/dendron-viz`
6. `npx dendron --version`
7. see no error

## Expected behavior

dendron-viz would be a dependency added via the yarn upgrade

## Desktop (please complete the following information)

- OS: Windows 8
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.102.0
  - VS Code version: NA
  - Dendron CLI: 0.102.0

## Additional context

```
npx dendron --version
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@dendronhq/dendron-viz'
Require stack:
- C:\Users\MYUSER\Documents\Git Repos\daio-documentation\node_modules\@dendronhq\dendron-cli\lib\src\commands\visualizeCLICommand.js
- C:\Users\MYUSER\Documents\Git Repos\daio-documentation\node_modules\@dendronhq\dendron-cli\lib\src\commands\index.js
- C:\Users\MYUSER\Documents\Git Repos\daio-documentation\node_modules\@dendronhq\dendron-cli\lib\bin\dendron-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\611192767\Documents\Git Repos\daio-documentation\node_modules\@dendronhq\dendron-cli\lib\src\commands\visualizeCLICommand.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\MYUSER\\Documents\\Git Repos\\daio-documentation\\node_modules\\@dendronhq\\dendron-cli\\lib\\src\\commands\\visualizeCLICommand.js',
    'C:\\Users\\MYUSER\\Documents\\Git Repos\\daio-documentation\\node_modules\\@dendronhq\\dendron-cli\\lib\\src\\commands\\index.js',
    'C:\\Users\\MYUSER\\Documents\\Git Repos\\daio-documentation\\node_modules\\@dendronhq\\dendron-cli\\lib\\bin\\dendron-cli.js'
  ]
}
```

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kevinslin** [comment]
fixed with release of 0.102.1
appreciate the quick catch!
